language: objective-c

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD
install:
    - pushd objc/VotingInformationProject && pod install
    - cp VotingInformationProject/CivicAPIKey.plist.template VotingInformationProject/CivicAPIKey.plist
    - cp VotingInformationProject/settings.plist.template VotingInformationProject/settings.plist

script:
    - xctool -workspace VotingInformationProject.xcworkspace -scheme VotingInformationProject -configuration Debug -sdk iphonesimulator -arch i386 test
    - popd
    - ./scripts/ci/check_copyright.sh
