platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs'

target 'VotingInformationProject' do
  pod 'Google-Maps-iOS-SDK',  '~> 1.8.1'
  pod 'MagicalRecord',        '~> 2.3'
  pod 'libPhoneNumber-iOS',   '~> 0.8'
  pod 'JSONModel',            '~> 1.0'
  pod 'GoogleAnalytics'
  pod 'AFNetworking',         '~> 2.0'
end

target 'VotingInformationProjectTests' do
  pod 'Kiwi'
end

